clear

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /afs/crc.nd.edu/user/b/bcheng4/Documents/1_research/privacy_preserving/PUF_RNG/inputs/data.txt
%
% Auto-generated by MATLAB on 08-Jul-2022 11:46:47

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data1 = readtable("/afs/crc.nd.edu/user/b/bcheng4/Documents/1_research/privacy_preserving/PUF_RNG/inputs/data100x100.txt", opts);
data2 = readtable("/afs/crc.nd.edu/user/b/bcheng4/Documents/1_research/privacy_preserving/PUF_RNG/inputs/data32x32.txt", opts);
data3 = readtable("/afs/crc.nd.edu/user/b/bcheng4/Documents/1_research/privacy_preserving/PUF_RNG/inputs/data16x16.txt", opts);

%% Convert to output type
data1 = table2array(data1);
data2 = table2array(data2);
data3 = table2array(data3);

%% Clear temporary variables
clear opts

%% 
COL = sqrt(length(data1));
ROW = COL;
vth100 = zeros(ROW, COL);
k = 1;
for i = 1:ROW
    for j = 1:COL
        vth100(i,j) = data1(k);
        k = k + 1;
    end
end

COL = sqrt(length(data2));
ROW = COL;
vth32 = zeros(ROW, COL);
k = 1;
for i = 1:ROW
    for j = 1:COL
        vth32(i,j) = data2(k);
        k = k + 1;
    end
end

COL = sqrt(length(data3));
ROW = COL;
vth16 = zeros(ROW, COL);
k = 1;
for i = 1:ROW
    for j = 1:COL
        vth16(i,j) = data3(k);
        k = k + 1;
    end
end

%% Heatmap
figure(1)
heatmap(vth100, "Colormap", parula);
xlabel("# of Bit-Line");
ylabel("# of Word-Line");
title("Threshold voltage heatmap");

figure(2)
heatmap(vth32, "Colormap", parula);
xlabel("# of Bit-Line");
ylabel("# of Word-Line");
title("Threshold voltage heatmap");

figure(3)
heatmap(vth16, "Colormap", parula);
xlabel("# of Bit-Line");
ylabel("# of Word-Line");
title("Threshold voltage heatmap");
